server:
  http:
    addr: 0.0.0.0:30005
    timeout: 3s
  grpc:
    addr: 0.0.0.0:30006
    timeout: 3s
data:
  database:
    driver: postgres
    source: postgresql://postgres:postgres@localhost:5432/database?sslmode=disable&timezone=Asia/Shanghai
  redis:
    addr: localhost:6379
    username:
    password:
    read_timeout: 3.0s
    write_timeout: 3.0s
    dial_timeout: 5s
