server:
  http:
    addr: 0.0.0.0:30001
    timeout: 3s
  grpc:
    addr: 0.0.0.0:30002
    timeout: 3s
data:
  database:
    driver: postgres
    source: postgresql://postgres:citus@localhost:5432/ecommence?sslmode=disable&timezone=Asia/Shanghai
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 3.0s
    write_timeout: 3.0s
    dial_timeout: 5s
