server:
  http:
    addr: 0.0.0.0:30003
    timeout: 3s
  grpc:
    addr: 0.0.0.0:30004
    timeout: 3s
data:
  database:
    driver: postgres
    source: postgresql://postgres:postgres@192.168.3.121:5432/ecommence?sslmode=disable&timezone=Asia/Shanghai
  redis:
    addr: 192.168.3.132:6379
    username: default
    password: msdnmm
    read_timeout: 3.0s
    write_timeout: 3.0s
    dial_timeout: 5s
