services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "0.0.0.0:5775:5775/udp"
      - "0.0.0.0:5778:5778"
      - "0.0.0.0:5779:5779"
      - "0.0.0.0:16686:16686"
      - "0.0.0.0:14269:14269"
      - "0.0.0.0:4317:4317"
      - "0.0.0.0:4318:4318"
