// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"backend/application/order/internal/biz"
	"backend/application/order/internal/conf"
	"backend/application/order/internal/data"
	"backend/application/order/internal/server"
	"backend/application/order/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, consul *conf.Consul,  observability *conf.Observability, logger log.Logger) (*kratos.App, func(), error) {
	pool := data.NewDB(confData)
	client := data.NewCache(confData)
	//casdoorsdkClient := data.NewCasdoor(auth)
	discovery, err := data.NewDiscovery(consul)

	cartServiceClient, err := data.NewCartServiceClient(discovery, logger)
	if err != nil {
		return nil, nil, err
	}

	dataData, cleanup, err := data.NewData(pool, client, cartServiceClient, logger)
	if err != nil {
		return nil, nil, err
	}
	
	userRepo := data.NewOrderrRepo(dataData, logger)
	userUsecase := biz.NewOrderUsecase(userRepo, logger)
	userService := service.NewOrderService(userUsecase)
	grpcServer := server.NewGRPCServer(confServer, observability, userService, logger)
	httpServer := server.NewHTTPServer(confServer, auth, userService, observability, logger)
	registrar := server.NewRegistrar(consul)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
