services:

  users:
    image: tiktok/users:prod
    platform: linux/amd64
    ports:
      - "30009:30009"
      - "30010:30010"
    container_name: orders
    restart: always
    networks:
      - app-network
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres12:5432/ecommence?sslmode=disable
      - REDIS_ADDRESS=redis7:6379
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=msdnmm
    command:
      - "/bin/user"
      - "-conf"
      - "/bin/configs"
